services:
  stubby-mockup:
    image: stubby-mockup:latest
    ports:
      - 8882:8882
      - 8889:8889
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yaml:/etc/ngrok.yml
    ports:
      - 4040:4040